Milestone 8: Integrations with fix
BenMKT/BlogApp pull request #8
Opened 2023-11-07 19:41 UTC by BenMKT

## Project implementations: 

- The N+1 problem is solved when fetching all posts and their comments for a user.
- Attached screenshots added before and after implementation:

Before fix: 
<img width="530" alt="BlogApp before fix" src="https://github.com/BenMKT/BlogApp/assets/118020802/1036c08b-2107-48a9-b801-5d8c276a6ae5">

After fix:
<img width="536" alt="Blog App after fix" src="https://github.com/BenMKT/BlogApp/assets/118020802/8e6bd2e7-52db-42dd-8249-7a3ad1e24b60">

- Write integration tests for each view file in the project

2023-11-07 22:08 UTC, frank1738 requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/hXz6GN0ZilLwhgLo49/giphy.gif"/>


## Highlights

✅ Successfully tested most "Views" scenarios
✅ Utilized "Capybara" effectively
✅ Impressive work on professional documentation
✅ Addressed the N+1 problem when fetching all posts and their comments 👍👏 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [ ] Check the comment below

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-07 22:08 UTC, ghost commented on spec/integration/user_index_spec.rb
> +end
- [x] 👋 Hi team! Great progress! 🚀 I just wanted to highlight that a test 🧪 that asserts you can see the user's `username` is missing. Kindly add it to fully meet the project requirements. 📸🙂

2023-11-07 22:08 UTC, ghost commented on spec/integration/post_index_spec.rb
> +end
#### In your `Post#Index`, Kindly include the following tests.
- [x] 🔍 A test that asserts you can see the user's profile picture. 📸👀
-  [x] 🔍 A test that asserts you can see the first comments on a post.👀

2023-11-07 22:08 UTC, ghost commented on spec/integration/user_show_spec.rb
> +  end
- [x] 📝 In your Post/#show, please add a test 🧪 that ensures you can see the post body. 📄👀

2023-11-07 22:08 UTC, ghost commented on spec/integration/post_index_spec.rb
> +  end
#### Optional

#### 👋 Hi team,

- [ optional] I wanted to suggest considering the use of describe blocks in our integration tests. It can enhance code organization and clarity by grouping related tests under meaningful headings, making it easier for everyone to understand the purpose of each test group. This organization can be particularly beneficial as our test suite grows and becomes more complex. 🧐👷‍♂️👷‍♀️

#### Keep up the great work! 👏🚀

2023-11-07 22:47 UTC, BenMKT commented on spec/integration/user_index_spec.rb
> +end
- Added a test that asserts you can see the user's username.

2023-11-07 23:12 UTC, BenMKT commented on spec/integration/post_index_spec.rb
> +end
- Added tests for both cases

2023-11-07 23:21 UTC, BenMKT commented on spec/integration/user_show_spec.rb
> +  end
- Added a test that ensures you can see the post body.

2023-11-07 23:36 UTC, BenMKT commented on spec/integration/post_index_spec.rb
> +  end
- Made use of describe blocks in our integration tests to enhance code organization and clarity.

2023-11-08 00:11 UTC, elisha2kyakpo1 approved these changes
Hi 👋 @BenMKT and @Rebelzob, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

👍 Great job fixing the changes requested by the previous reviewer.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-08 00:17 UTC, merged